# Generated by Django 3.0.5 on 2020-04-02 14:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='story',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
